// A practical (not exhaustive) list of countries for the phone input,
// covering East Africa first (primary market) then major source markets
// for international tourism to Kenya, then the rest alphabetically.

export const countryCodes = [
  { iso: "KE", name: "Kenya", dial: "+254" },
  { iso: "UG", name: "Uganda", dial: "+256" },
  { iso: "TZ", name: "Tanzania", dial: "+255" },
  { iso: "RW", name: "Rwanda", dial: "+250" },
  { iso: "ET", name: "Ethiopia", dial: "+251" },
  { iso: "SO", name: "Somalia", dial: "+252" },
  { iso: "US", name: "United States", dial: "+1" },
  { iso: "GB", name: "United Kingdom", dial: "+44" },
  { iso: "DE", name: "Germany", dial: "+49" },
  { iso: "FR", name: "France", dial: "+33" },
  { iso: "IT", name: "Italy", dial: "+39" },
  { iso: "ES", name: "Spain", dial: "+34" },
  { iso: "NL", name: "Netherlands", dial: "+31" },
  { iso: "CH", name: "Switzerland", dial: "+41" },
  { iso: "SE", name: "Sweden", dial: "+46" },
  { iso: "NO", name: "Norway", dial: "+47" },
  { iso: "DK", name: "Denmark", dial: "+45" },
  { iso: "BE", name: "Belgium", dial: "+32" },
  { iso: "IE", name: "Ireland", dial: "+353" },
  { iso: "PT", name: "Portugal", dial: "+351" },
  { iso: "AT", name: "Austria", dial: "+43" },
  { iso: "PL", name: "Poland", dial: "+48" },
  { iso: "CA", name: "Canada", dial: "+1" },
  { iso: "AU", name: "Australia", dial: "+61" },
  { iso: "NZ", name: "New Zealand", dial: "+64" },
  { iso: "JP", name: "Japan", dial: "+81" },
  { iso: "CN", name: "China", dial: "+86" },
  { iso: "IN", name: "India", dial: "+91" },
  { iso: "SG", name: "Singapore", dial: "+65" },
  { iso: "AE", name: "United Arab Emirates", dial: "+971" },
  { iso: "SA", name: "Saudi Arabia", dial: "+966" },
  { iso: "QA", name: "Qatar", dial: "+974" },
  { iso: "IL", name: "Israel", dial: "+972" },
  { iso: "ZA", name: "South Africa", dial: "+27" },
  { iso: "NG", name: "Nigeria", dial: "+234" },
  { iso: "GH", name: "Ghana", dial: "+233" },
  { iso: "EG", name: "Egypt", dial: "+20" },
  { iso: "MA", name: "Morocco", dial: "+212" },
  { iso: "BR", name: "Brazil", dial: "+55" },
  { iso: "MX", name: "Mexico", dial: "+52" },
  { iso: "AR", name: "Argentina", dial: "+54" },
  { iso: "RU", name: "Russia", dial: "+7" },
  { iso: "KR", name: "South Korea", dial: "+82" },
  { iso: "TH", name: "Thailand", dial: "+66" },
  { iso: "MY", name: "Malaysia", dial: "+60" },
  { iso: "PH", name: "Philippines", dial: "+63" },
  { iso: "ID", name: "Indonesia", dial: "+62" },
  { iso: "TR", name: "Turkey", dial: "+90" },
  { iso: "GR", name: "Greece", dial: "+30" },
  { iso: "FI", name: "Finland", dial: "+358" },
  { iso: "CZ", name: "Czechia", dial: "+420" },
  { iso: "ZM", name: "Zambia", dial: "+260" },
  { iso: "ZW", name: "Zimbabwe", dial: "+263" },
  { iso: "MW", name: "Malawi", dial: "+265" },
  { iso: "OTHER", name: "Other / not listed", dial: "+" }
];

export function countryByIso(iso) {
  return countryCodes.find((c) => c.iso === iso);
}
